### ISSUE TITLE
[Workings] Massive Refactor and additional calls/objects

### ISSUE THREAD

**Issue by F9Alejandro** [cf-discord/cloudflare-discord-bot#23]
Been busy with getting the code refactored in a way that makes it easier for use and to help solve the issue of a large types file. (new ./applications folder with files breaking down the types by category). Also been busy with getting more types/interfaces and objects that implements, and handles more of the discord api when information is received. Will work on getting more done.

**Comment by Inrixia** [comment]
Hey, I already have a PR open that handles switching to the official discord api types and improves on various things. I suggest checking out and probably working off my fork which is the process of being merged before moving forward

**Comment by F9Alejandro** [comment]
Then there is me with all the fun stuff.
Take a look at this
https://github.com/F9Alejandro/cf-discord-js let me know what you think. obviously it needs work lol

**Comment by Inrixia** [comment]
That looks great

**Comment by Inrixia** [comment]
@F9Alejandro I have opened several issues on your repo pertaining to issues I ran into and fixed with this library. I suggest looking over all my changes in this PR https://github.com/alvgaona/cloudflare-discord-bot/pull/14

**Comment by F9Alejandro** [comment]
Thank you for helping me out with this. I will like to see if you would be willing to assist with the move over from autocode to cloudflare workers. also feel free to add me on discord Fang_Shadow#9903

**Comment by F9Alejandro** [comment]
@Inrixia I have decided to use your library instead of this one since it is more up to date and has better handling due to the discord-types-api from discordjs. All I did for my environment is just added loglevel to see what it is doing with debug code. (going to turn it off of debug to warn) but it is a great way of figuring out what is going on.
